// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhjuy-1xfKyk9znrHftHox-z1Gue6mb-A',
    appId: '1:168398973524:web:b2b2a925302c47d1ef5bc1',
    messagingSenderId: '168398973524',
    projectId: 'flutterdictionary-30740',
    authDomain: 'flutterdictionary-30740.firebaseapp.com',
    storageBucket: 'flutterdictionary-30740.appspot.com',
    measurementId: 'G-0J6C1N5ZGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7rUITHd9gOsxUxOl5gOs9AR3qqiX8QzA',
    appId: '1:168398973524:android:344a02c937f42990ef5bc1',
    messagingSenderId: '168398973524',
    projectId: 'flutterdictionary-30740',
    storageBucket: 'flutterdictionary-30740.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKhOQ_UyzG-eKCoCgZ1xruC4WD4wtcnEU',
    appId: '1:168398973524:ios:46f23a72da43b31def5bc1',
    messagingSenderId: '168398973524',
    projectId: 'flutterdictionary-30740',
    storageBucket: 'flutterdictionary-30740.appspot.com',
    iosClientId: '168398973524-3m86l0d2nfsmkpat7corl2oa9ufmpea3.apps.googleusercontent.com',
    iosBundleId: 'com.example.dictionaryFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKhOQ_UyzG-eKCoCgZ1xruC4WD4wtcnEU',
    appId: '1:168398973524:ios:8b8a5266753a74c4ef5bc1',
    messagingSenderId: '168398973524',
    projectId: 'flutterdictionary-30740',
    storageBucket: 'flutterdictionary-30740.appspot.com',
    iosClientId: '168398973524-6geh3q7mv7f8a9tf8eqa3h6cql7nansq.apps.googleusercontent.com',
    iosBundleId: 'com.example.dictionaryFlutter.RunnerTests',
  );
}
